version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1-node
    working_directory: ~/notquitepure.io
    steps:
      - checkout
      - run:
          name: Git Submodule Init
          command: |
            git submodule init
            git submodule update
      - run:
          name: Install Hexo CLI
          command: yarn global add hexo-cli
      - restore_cache:
          keys:
            - hexo-deps-v2-{{ checksum "yarn.lock" }}
      - run:
          name: Install Hexo Dependencies
          command: yarn install
      - save_cache:
          key: hexo-deps-v2-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - restore_cache:
          keys:
            - typography-deps-v2-{{ checksum "themes/typography/yarn.lock" }}
      - run:
          name: Install Hexo Dependencies
          command: |
            cd themes/typography
            yarn install
      - save_cache:
          key: typography-deps-v2-{{ checksum "themes/typography/yarn.lock" }}
          paths:
            - themes/typography/node_modules
      - run:
          name: Generate static website
          command: hexo generate
      - run:
          name: Install AWS CLI
          command: |
            pip install awscli --upgrade --user
      - run:
          name: Push to S3 bucket
          command: |
            export PATH=~/.local/bin:$PATH
            source ~/.profile
            aws configure list
            aws --version
            cd public
            aws s3 sync . s3://notquitepure.info --delete --acl public-read